### ISSUE TITLE
La promessa 10 viene renderizzata male

### ISSUE THREAD

**Issue by aborruso** [HackForItaly/politicamentecorretto#16]
Qui l'output https://unapromessa.it/issues/10/ (senza la dichiarazione).

Qui la issue https://github.com/HackForItaly/politicamentecorretto_data/issues/10

**Comment by mfortini** [comment]
Ho fixato un problema laterale, quello del fatto che i doppi apici e le doppie virgolette vengono renderizzate come tali, quindi li ho sostituiti con le versioni singole.

@aborruso un problema è che enketo fa l'encoding delle stringhe con i singoli apici come quote, ma all'interno se c'è un apostrofo rompe tutto lo YAML

**Comment by aborruso** [comment]
@mfortini ho incollato il testo di sotto qui https://yamlchecker.com/ e me lo da valido. Che sbaglio?

```
Nome: 'Nicola Fratoianni'
data: 13/01/2018
Nome fonte: 'Pagina facebook'
urlfonte: 'https://www.facebook.com/Fratoianni/posts/1352244441546114'
dichiarazione: '- Cancellazione del Jobs Act e del decreto Poletti; - Ripristino dell''articolo 18; - Abolizione della precarietà; - Un Piano per il lavoro e per gli investimenti a tutela del territorio, del patrimonio edilizio e delle opere utili; - No al lavoro gratuito o sottopagato; - Tutela dei lavoratori in appalto e subappalto e contrasto a finte cooperative e finte imprese. E poi la protezione dei lavoratori dagli effetti della globalizzazione: - applicazione del Contratto Collettivo Nazionale per tutti; - sanzioni per le imprese che delocalizzano; - dazi per le imprese extra-UE che non rispettano i lavoratori e l''ambiente; - Messa in discussione di trattati di libero scambio (CETA e TTIP).'
```

**Comment by mfortini** [comment]
Scusa @aborruso è che l'ho corretto a mano per farlo funzionare sul sito, in originale gli apici erano singoli

**Comment by aborruso** [comment]
@mfortini nel caso di una stringa come:

    Dichiara che vorrebbe il "Ripristino dell'articolo 18" prima di natale

come è bene che sia in YAML?

Così?

    dichirazione: "Dichiara che vorrebbe il \"Ripristino dell'articolo 18\" prima di natale"


Grazie

**Comment by aborruso** [comment]
Caro @mfortini facciamo un primo check.

Immaginiamo che nel form venga scritta questa bruttura:

    "L'aria, è pesante" ha detto " ' l'onorevole "Mandrake "" '' il magnifico

Un output YAML valido (in cui ho inserito altri due campi) è:

```YAML
- nome: Ciccio
  dichiarazione: '"L''aria, è pesante" ha detto " '' l''onorevole "Mandrake "" ''''
    il magnifico'
  account: '@ciccio'
```

Nel caso di un più normale

    "L'aria, è pesante" ha detto l'onorevole "Mandrake" il magnifico

l'output YAML è

```YAML
- nome: Ciccio
  dichiarazione: '"L''aria, è pesante" ha detto l''onorevole "Mandrake" il magnifico'
  account: '@ciccio'
```

Per te va bene?

Grazie
